fix config yml

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -21,32 +21,37 @@ jobs:
     runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
-    - name: Login
-      uses: atlassian/gajira-login@v3
-      env:
-        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
-        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
-        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
 
-    - name: Find Issue Key
-      uses: ./
-      with:
-        from: commits
+      # Steps represent a sequence of tasks that will be executed as part of the job
+      - name: Login
+        uses: atlassian/gajira-login@v3
+        env:
+          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
+          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
+          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
 
-    - name: Find Issue Key
-      id: find
-      uses: ./
-      with:
-        string: Search is performed in this string. FIND-1 will be found
+      - name: Find Issue Key
+        uses: ./
+        with:
+          from: commits
 
-    - name: Find Issue Key
-      uses: ./
-      with:
-        string: ${{ github.event.ref }} will search in branch name
+      - name: Find Issue Key
+        id: find
+        uses: ./
+        with:
+          string: Search is performed in this string. FIND-1 will be found
 
-    - name: should skip if working, or else error out
-      if: ${{ steps.find.outputs.issue == '' }}
-      run: echo "Issue not found" && exit 1
+      - name: Find Issue Key
+        uses: ./
+        with:
+          string: ${{ github.event.ref }} will search in branch name
 
-    - name: Find issue info
-      run: echo "Issue ${{ steps.find.outputs.issue }} was found"
+      - name: should skip if working, or else error out
+        if: ${{ steps.find.outputs.issue == '' }}
+        run: echo "Issue not found" && exit 1
+
+      - name: Find issue info
+        run: echo "Issue ${{ steps.find.outputs.issue }} was found"
